services:
  db:
    container_name: sleep_db
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - ./resources/sql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sleep_db

  smtp:
    container_name: sleep_smtp
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025